# Generated by Django 6.0.7 on 2026-10-01 10:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_core', '0001_initial'),
        ('erp_masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCountSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('document_no', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(db_index=True, default='draft', max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required when rejecting a document')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('zone_filter', models.CharField(blank=True, help_text='Specific zone or blank for full warehouse', max_length=100)),
                ('blind_count', models.BooleanField(default=True, help_text='Counters cannot see expected system quantity')),
                ('count_status', models.CharField(choices=[('DRAFT', 'Draft'), ('FROZEN', 'Scope Frozen for Count'), ('IN_PROGRESS', 'Counting in Progress'), ('SUBMITTED', 'Counts Submitted, Variance Calculated'), ('APPROVED', 'Variances Approved by Finance/QA'), ('POSTED', 'Adjustments Posted to Stock Ledger')], default='DRAFT', max_length=30)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('lot_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('batch_no', models.CharField(db_index=True, help_text='Batch number (never recycled)', max_length=60)),
                ('supplier_lot_no', models.CharField(blank=True, max_length=100)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('retest_date', models.DateField(blank=True, null=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('quantity_reserved', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('QUARANTINE', 'Quarantine (Pending QC Inspection)'), ('AVAILABLE', 'Available / Released (Approved for use/sale)'), ('RESERVED', 'Reserved (Allocated to Order)'), ('REJECTED', 'Rejected (Failed QC / Segregated)'), ('BLOCKED', 'Blocked (Under Hold / Investigation)'), ('EXPIRED', 'Expired (Past Shelf Life)'), ('RECALLED', 'Recalled (Under Product Recall)'), ('IN_TRANSIT', 'In-Transit between sites')], db_index=True, default='QUARANTINE', max_length=30)),
                ('qc_reference', models.CharField(blank=True, help_text='QC Analytical Report Number / COA', max_length=100)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='erp_masters.storagebin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='erp_masters.itemmaster')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_lots', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_masters.suppliermaster')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='erp_masters.warehouse')),
            ],
            options={
                'verbose_name': 'Inventory Lot / Batch',
                'verbose_name_plural': 'Inventory Lots & Batches',
                'ordering': ['expiry_date', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('system_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('variance_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('recount_required', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_masters.storagebin')),
                ('counter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.itemmaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp_inventory.cyclecountsession')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_inventory.inventorylot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('GRN_RECEIPT', 'Goods Receipt Note (Quarantine Inward)'), ('QC_RELEASE', 'QC Inspection Release to Stock'), ('QC_REJECT', 'QC Inspection Rejection'), ('MATERIAL_ISSUE', 'Issue to Production Batch'), ('PRODUCTION_RECEIPT', 'Receipt of Finished Goods from Production'), ('TRANSFER_IN', 'Warehouse Transfer Inward'), ('TRANSFER_OUT', 'Warehouse Transfer Outward'), ('DISPATCH', 'Sales Dispatch / Customer Invoice'), ('CUSTOMER_RETURN', 'Customer Return Quarantine Inward'), ('ADJUSTMENT_PLUS', 'Approved Physical Count Positive Adjustment'), ('ADJUSTMENT_MINUS', 'Approved Physical Count Negative Adjustment'), ('RECALL_BLOCK', 'Batch Regulatory Recall Block')], db_index=True, max_length=30)),
                ('document_no', models.CharField(db_index=True, help_text='Source Document (PO, GRN, BMR, INV)', max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('reason', models.TextField(blank=True)),
                ('from_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bin_out_entries', to='erp_masters.storagebin')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_out_entries', to='erp_masters.warehouse')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='erp_masters.itemmaster')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='erp_inventory.inventorylot')),
                ('to_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bin_in_entries', to='erp_masters.storagebin')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_in_entries', to='erp_masters.warehouse')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.unitofmeasure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Ledger Entry',
                'verbose_name_plural': 'Stock Ledger Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
