# Generated by Django 6.0.7 on 2026-10-01 10:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_core', '0001_initial'),
        ('erp_inventory', '0001_initial'),
        ('erp_masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('document_no', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required when rejecting a document')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('requested_delivery_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Entry'), ('SUBMITTED', 'Submitted for Credit Check'), ('APPROVED', 'Credit Approved, Stock Reserved via FEFO'), ('PICKING', 'Pick List Generated'), ('DISPATCHED', 'Invoiced & Dispatched'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('credit_override', models.BooleanField(default=False)),
                ('credit_override_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='erp_masters.customermaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesDispatchInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('document_no', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(db_index=True, default='draft', max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required when rejecting a document')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('transporter_name', models.CharField(blank=True, max_length=150)),
                ('docket_no', models.CharField(blank=True, help_text='Courier / Lorry Receipt (LR) number', max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('eway_bill_no', models.CharField(blank=True, help_text='Government E-Way Bill Number', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('is_paid', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.customermaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='erp_sales.salesorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('ordered_qty', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp_sales.salesorder')),
                ('product', models.ForeignKey(limit_choices_to={'item_type': 'FINISHED_GOOD'}, on_delete=django.db.models.deletion.PROTECT, to='erp_masters.itemmaster')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLotAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('allocated_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('is_dispatched', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_allocations', to='erp_sales.salesorderline')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_inventory.inventorylot')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
