# Generated by Django 6.0.7 on 2026-10-01 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('lead_id', models.CharField(db_index=True, editable=False, max_length=60, unique=True)),
                ('lead_type', models.CharField(choices=[('DISTRIBUTOR', 'Distributor / Wholesaler'), ('STOCKIST', 'Stockist / C&F'), ('RETAILER', 'Retail Chemist / Pharmacy'), ('HOSPITAL', 'Hospital / Medical Center'), ('CLINIC', 'Doctor Clinic'), ('INSTITUTIONAL', 'Institutional / Government Buyer'), ('OTHER', 'Other')], default='DISTRIBUTOR', max_length=30)),
                ('organization_name', models.CharField(db_index=True, max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('territory', models.CharField(blank=True, max_length=100)),
                ('tax_or_drug_license', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='Field Inquiry', help_text='e.g. Website, Medical Expo, Field Call', max_length=100)),
                ('stage', models.CharField(choices=[('NEW', 'New Lead'), ('CONTACTED', 'Initial Contact Made'), ('FOLLOW_UP', 'Active Follow-Up'), ('QUALIFIED', 'Qualified Prospect'), ('QUOTATION', 'Quotation / Commercial Proposal Sent'), ('CONVERTED', 'Converted to Customer'), ('LOST', 'Lost Opportunity')], db_index=True, default='NEW', max_length=30)),
                ('next_follow_up_date', models.DateField(blank=True, db_index=True, null=True)),
                ('lost_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('activity_type', models.CharField(choices=[('CALL', 'Phone Call'), ('VISIT', 'In-Person Detailing / Visit'), ('EMAIL', 'Email Follow-up / Quotation'), ('MEETING', 'Commercial Negotiation Meeting')], default='CALL', max_length=20)),
                ('purpose', models.CharField(max_length=255)),
                ('due_date', models.DateField(db_index=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending / Scheduled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('outcome_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='erp_crm.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('batch_no', models.CharField(max_length=60, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('import_summary', models.JSONField(default=dict)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
