# Generated by Django 6.0.7 on 2026-10-08 09:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0001_initial'),
        ('erp_crm', '0002_alter_followuptask_assigned_to'),
        ('erp_hr', '0001_initial'),
        ('erp_masters', '0002_warehouse_warehouse_type'),
        ('erp_sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBeatPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(db_index=True, editable=False, max_length=60, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('planned_time', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_beats', to='erp_masters.customermaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beat_plans', to='erp_hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'sequence'],
                'unique_together': {('employee', 'date', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('document_no', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(db_index=True, default='draft', max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required when rejecting a document')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('visit_no', models.CharField(db_index=True, editable=False, max_length=60, unique=True)),
                ('visit_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('visit_status', models.CharField(choices=[('PLANNED', 'Planned / Scheduled'), ('IN_PROGRESS', 'In Progress (Active Visit)'), ('COMPLETED', 'Completed & Submitted'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('start_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_accuracy', models.FloatField(blank=True, null=True)),
                ('distance_to_target_meters', models.FloatField(blank=True, null=True)),
                ('geofence_status', models.CharField(choices=[('VALID', 'Verified Inside Geofence'), ('OUTSIDE_GEOFENCE', 'Outside Target Geofence Boundary'), ('NO_COORDINATES', 'Target Has No Coordinates Set'), ('REQUIRES_REVIEW', 'Requires Manager Review (Poor GPS)')], db_index=True, default='VALID', max_length=30)),
                ('geofence_deviation_reason', models.TextField(blank=True, help_text='Mandatory justification when starting outside geofence boundary')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_accuracy', models.FloatField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('doctor_response', models.CharField(blank=True, choices=[('HIGHLY_INTERESTED', 'Highly Interested / Prescribing Core Brands'), ('POSITIVE', 'Positive / Agreed to Trial Prescriptions'), ('NEUTRAL', 'Neutral / Existing Stocks Present'), ('NOT_INTERESTED', 'Not Interested Currently'), ('BUSY', 'Doctor / Chemist Busy, Requested Reschedule')], max_length=30)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('beat_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='erp_crm.dailybeatplan')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_visits', to='erp_masters.customermaster')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_visits', to='erp_hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitOrderBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('booked_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_bookings', to='erp_sales.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_booked', to='erp_crm.fieldvisit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitProductDiscussed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('is_core_focus', models.BooleanField(default=True)),
                ('feedback', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(limit_choices_to={'item_type': 'FINISHED_GOOD'}, on_delete=django.db.models.deletion.PROTECT, to='erp_masters.itemmaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_discussed', to='erp_crm.fieldvisit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitSampleGiven',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('batch_no', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(limit_choices_to={'item_type': 'FINISHED_GOOD'}, on_delete=django.db.models.deletion.PROTECT, to='erp_masters.itemmaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples_given', to='erp_crm.fieldvisit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeLocationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Daily Duty Check-In'), ('CHECK_OUT', 'Daily Duty Check-Out'), ('VISIT_START', 'Visit Started'), ('VISIT_END', 'Visit Finished'), ('LOCATION_PING', 'Periodic Verified Ping'), ('OFFLINE_SYNC', 'Offline Sync Event')], db_index=True, max_length=20)),
                ('server_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device_timestamp', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.FloatField()),
                ('battery_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_mock', models.BooleanField(default=False)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('geofence_status', models.CharField(blank=True, max_length=30)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_events', to='erp_hr.employee')),
            ],
            options={
                'ordering': ['-server_timestamp'],
                'indexes': [models.Index(fields=['employee', 'server_timestamp'], name='erp_crm_emp_employe_235a62_idx'), models.Index(fields=['event_type', 'server_timestamp'], name='erp_crm_emp_event_t_bc1bbc_idx'), models.Index(fields=['idempotency_key'], name='erp_crm_emp_idempot_b73fbe_idx')],
            },
        ),
    ]
