# Generated by Django 6.0 on 2026-06-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_price_product_selling_price_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
