# Generated by Django 6.0.7 on 2026-10-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='battery_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_status',
            field=models.CharField(choices=[('VALID', 'Valid Check-In'), ('POOR_ACCURACY', 'Poor GPS Accuracy'), ('REQUIRES_REVIEW', 'Requires Manager Review'), ('MANUAL', 'Manual Punch')], default='VALID', max_length=30),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_status',
            field=models.CharField(blank=True, choices=[('VALID', 'Valid Check-Out'), ('POOR_ACCURACY', 'Poor GPS Accuracy'), ('REQUIRES_REVIEW', 'Requires Manager Review')], max_length=30),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_mock_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='work_mode',
            field=models.CharField(choices=[('FIELD', 'Field Work / Doctor Detailing'), ('OFFICE', 'Branch / Plant Office'), ('TRANSIT', 'Travel / Tour')], default='FIELD', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Reporting manager / Area Sales Manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='erp_hr.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sales_tier',
            field=models.CharField(choices=[('MR', 'Medical Representative / Field Officer'), ('ASM', 'Area Sales Manager'), ('RSM', 'Regional Sales Manager'), ('NSM', 'National Sales Manager'), ('EXECUTIVE', 'Commercial Sales Executive')], db_index=True, default='MR', help_text='Field force hierarchy rank', max_length=30),
        ),
    ]
