# Generated by Django 6.0.7 on 2026-10-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_hr', '0002_attendancerecord_battery_level_and_more'),
        ('erp_masters', '0003_alter_customermaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='territory',
            field=models.ForeignKey(blank=True, help_text='Assigned commercial sales territory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='erp_masters.territory'),
        ),
    ]
