# Generated by Django 6.0.7 on 2026-10-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('GENERAL', 'General Ambient Warehouse'), ('COLD_CHAIN', 'Cold Chain (2°C - 8°C)'), ('QUARANTINE', 'Quarantine Holding Area'), ('FINISHED_GOODS', 'Finished Goods Central'), ('RAW_MATERIALS', 'Raw Materials / Active Ingredients Bay')], default='GENERAL', max_length=30),
        ),
    ]
