# Generated by Django 6.0.7 on 2026-10-08 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0001_initial'),
        ('erp_hr', '0002_attendancerecord_battery_level_and_more'),
        ('erp_masters', '0002_warehouse_warehouse_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermaster',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customermaster',
            name='geofence_radius_meters',
            field=models.PositiveIntegerField(default=150, help_text='Geofence boundary radius in meters'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(db_index=True, help_text='e.g. TERR-DEL-01, TERR-NOIDA', max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('headquarters', models.CharField(help_text='HQ City, e.g. Noida, Delhi-NCR, Lucknow', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('NORTH', 'North Zone'), ('SOUTH', 'South Zone'), ('EAST', 'East Zone'), ('WEST', 'West Zone'), ('CENTRAL', 'Central Zone')], default='NORTH', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='territories', to='erp_core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text='Area / Regional Sales Manager overseeing territory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_territories', to='erp_hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Territory',
                'verbose_name_plural': 'Territories',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='customermaster',
            name='territory',
            field=models.ForeignKey(blank=True, help_text='Assigned commercial sales territory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='erp_masters.territory'),
        ),
    ]
