# Generated by Django 6.0.7 on 2026-10-01 10:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_core', '0001_initial'),
        ('erp_inventory', '0001_initial'),
        ('erp_masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('document_no', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required when rejecting a document')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('batch_no', models.CharField(db_index=True, max_length=60, unique=True)),
                ('planned_qty', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('actual_produced_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('scrap_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('manufacturing_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('yield_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Planning'), ('RELEASED', 'Supervisor Released (BMR Issued)'), ('IN_PROGRESS', 'Manufacturing In-Progress'), ('COMPLETED', 'Batch Completed, Submitted to QC'), ('CLOSED', 'QA Dispositioned & Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.bomheader')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('finished_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_source', to='erp_inventory.inventorylot')),
                ('product', models.ForeignKey(limit_choices_to={'item_type__in': ['WIP', 'FINISHED_GOOD']}, on_delete=django.db.models.deletion.PROTECT, to='erp_masters.itemmaster')),
                ('target_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_masters.storagebin')),
                ('target_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.warehouse')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('step_name', models.CharField(max_length=150)),
                ('sop_reference', models.CharField(blank=True, help_text='Standard Operating Procedure code', max_length=100)),
                ('equipment_id', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('in_process_check_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_steps', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_steps', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='erp_manufacturing.productionorder')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='BatchMaterialConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('standard_required_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('actual_consumed_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('variance_reason', models.CharField(blank=True, max_length=255)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.itemmaster')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_inventory.inventorylot')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='erp_manufacturing.productionorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
