# Generated by Django 6.0.7 on 2026-10-01 10:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. SITE-01, WH-DELHI', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('site_type', models.CharField(choices=[('manufacturing', 'Manufacturing Site'), ('warehouse', 'Central / Regional Warehouse'), ('office', 'Corporate / Sales Office'), ('rnd', 'R&D / QC Laboratory')], default='manufacturing', max_length=30)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('gstin', models.CharField(blank=True, help_text='Tax / GST Identification Number', max_length=20)),
                ('drug_license_no', models.CharField(blank=True, help_text='Site Drug License Number', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches & Sites',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('CREATE', 'Created Record'), ('UPDATE', 'Updated Record'), ('DELETE_ATTEMPT', 'Blocked Delete Attempt'), ('APPROVE', 'Authorized Approval'), ('REJECT', 'Rejected with Reason'), ('POST', 'Financial / Stock Ledger Posted'), ('DISPATCH', 'Material Dispatched'), ('QA_RELEASE', 'QA Batch Released'), ('QA_REJECT', 'QA Batch Rejected'), ('QA_HOLD', 'QA Quarantine / Hold Imposed'), ('RECALL', 'Product Batch Recalled'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('SECURITY_ALERT', 'Security Exception / Violation')], max_length=30)),
                ('entity_name', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('document_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('reason', models.TextField(blank=True, help_text='Mandatory for overrides, corrections, rejections')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Structured before/after diff')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_core.branch')),
            ],
            options={
                'verbose_name': 'Audit Trail Record',
                'verbose_name_plural': 'Audit Trail Records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('response_code', models.IntegerField(null=True)),
                ('response_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20)),
                ('financial_year', models.CharField(help_text='e.g. 2026-27 or 2026', max_length=10)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_core.branch')),
            ],
            options={
                'unique_together': {('prefix', 'financial_year', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='ERPUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'System Administrator'), ('PURCHASE', 'Purchase Officer / Manager'), ('WAREHOUSE', 'Warehouse & Inventory Manager'), ('PRODUCTION', 'Production Officer / Planner'), ('QC_ANALYST', 'Quality Control (QC) Analyst'), ('QA_APPROVER', 'Quality Assurance (QA) Approver'), ('SALES_CRM', 'Sales & CRM Representative'), ('ACCOUNTS', 'Finance & Accounts Officer'), ('HR_PAYROLL', 'HR & Payroll Manager'), ('AUDITOR', 'Regulatory & Compliance Auditor (Read-Only)')], max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Scope to branch or null for all', null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_core.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User ERP Role',
                'verbose_name_plural': 'User ERP Roles',
                'unique_together': {('user', 'role', 'branch')},
            },
        ),
    ]
