# Generated by Django 6.0.7 on 2026-10-01 10:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_core', '0001_initial'),
        ('erp_inventory', '0001_initial'),
        ('erp_masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('document_no', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required when rejecting a document')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('CLASS_I', 'Class I (Dangerous / Defective with health hazard)'), ('CLASS_II', 'Class II (Temporary or medically reversible hazard)'), ('CLASS_III', 'Class III (Unlikely to cause adverse health consequences)')], max_length=20)),
                ('recall_reason', models.TextField()),
                ('total_distributed_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('total_reconciled_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('status', models.CharField(default='INITIATED', max_length=30)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recalls', to='erp_inventory.inventorylot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QCInspectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('document_no', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required when rejecting a document')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sample_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('sample_uom_code', models.CharField(default='GM', max_length=20)),
                ('sampled_at', models.DateTimeField(blank=True, null=True)),
                ('sampling_plan', models.CharField(default='Square root of N + 1 (WHO/GMP)', max_length=100)),
                ('testing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_test_result', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Passes All Tests'), ('FAIL', 'Out of Specification (OOS)')], default='PENDING', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_SAMPLING', 'Pending Sample Collection'), ('SAMPLED', 'Sample Collected, Under Testing'), ('TESTING_COMPLETED', 'Testing Completed, Pending QA Review'), ('DISPOSITIONED', 'Quality Disposition Executed')], db_index=True, default='PENDING_SAMPLING', max_length=30)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_tests', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.itemmaster')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspections', to='erp_inventory.inventorylot')),
                ('sampler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_samples', to=settings.AUTH_USER_MODEL)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.qualityspecification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QADispositionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('document_no', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(db_index=True, default='draft', max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required when rejecting a document')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disposition', models.CharField(choices=[('RELEASE', 'Authorized Batch Release to Commercial Stock'), ('REJECT', 'Rejected / Segregated for Destruction'), ('HOLD', 'Quarantine Hold (Pending Investigation)')], max_length=20)),
                ('disposition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('decision_reason', models.TextField(help_text='Detailed regulatory rationale for disposition')),
                ('coa_number', models.CharField(blank=True, help_text='Certificate of Analysis (COA) number', max_length=100)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('authorized_qa_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executed_qa_dispositions', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_dispositions', to='erp_inventory.inventorylot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qa_disposition', to='erp_quality.qcinspectionrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QCTestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('raw_result_value', models.CharField(help_text='Textual or numerical analytical result, e.g. 99.4%', max_length=255)),
                ('numerical_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_compliant', models.BooleanField(default=True)),
                ('is_oos', models.BooleanField(default=False, help_text='Out of Specification flag')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='erp_quality.qcinspectionrequest')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp_masters.specificationparameter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualityDeviation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version counter')),
                ('is_active', models.BooleanField(default=True)),
                ('document_no', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Required when rejecting a document')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('deviation_title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor (No direct product quality impact)'), ('MAJOR', 'Major (Potential impact, requires full investigation)'), ('CRITICAL', 'Critical (Direct regulatory/patient safety risk)')], default='MINOR', max_length=20)),
                ('immediate_containment', models.TextField(help_text='Immediate action taken to contain material')),
                ('root_cause', models.TextField(blank=True, help_text='5-Why or Fishbone root cause analysis')),
                ('impact_assessment', models.TextField(blank=True)),
                ('status', models.CharField(default='OPEN', max_length=30)),
                ('affected_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_inventory.inventorylot')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp_core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
